-- Core
require('core/settings')
require('core/mappings')
require('packer-init')
-- Plugins
require('plugins/treesitter-config')
require('plugins/telescope-config')
require('plugins/lsp-installer-config')
require('plugins/lsp-config')
require('plugins/nvimtree-config')
require('plugins/neorg-config')
require('plugins/styles-config')
require('plugins/lualine-config')
require('plugins/barbar-config')
require('plugins/flake-config')
require('plugins/vimtex-config')
require('plugins/alpha-config')
